In [2]:
!pip install utm

Collecting utm
  Downloading utm-0.7.0.tar.gz (8.7 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: utm
  Building wheel for utm (setup.py): started
  Building wheel for utm (setup.py): finished with status 'done'
  Created wheel for utm: filename=utm-0.7.0-py3-none-any.whl size=6105 sha256=ffcb87eb0cc227af63fb49d7ba3ae87a840dbbbaa6b704cacad7331096987954
  Stored in directory: c:\users\kuion\appdata\local\pip\cache\wheels\2f\a1\c8\543df0e8f5e824c3e92a432e32deb9cd89ae686095ee8cfcbe
Successfully built utm
Installing collected packages: utm
Successfully installed utm-0.7.0

In [4]:
import utm
import pandas as pd

C:\Users\kuion\AppData\Local\Temp\ipykernel_10168\2304427805.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [46]:
filepath="C:\\Users\\kuion\\OneDrive\\Dokumendid\\MadridMapConv\\MADRID ZBE. Photo-red devices located on roads inside the M-30.tsv"

In [49]:
def utm2LonLat(row):
    # print(row.index)
    # print(utm.to_latlon(row["UTM_X"], row["UTM_Y"], 30, 'T'))
    lat, lon = utm.to_latlon(row["UTM_X"], row["UTM_Y"], 30, 'T')
    row["LATITUD"] = lat
    row["LONGITUD"] = lon
    return row

In [50]:
df = pd.read_csv(filepath_or_buffer=filepath, delimiter="\t", thousands=',')
# print(df)
df = df.apply(utm2LonLat, axis=1)
# print(df)
df#["LATITUD"]

,COD_FOTO_R,COD_CRUCE_,NOMBRE,FECHA_DENU,UTM_X,UTM_Y,LATITUD,LONGITUD
0,724,701,ALBERTO AGUILERA - BALTASAR GRACIÁN,26/09/2016,439697.11,4475730.96,40.430032,-3.710933
1,1471,702,AVDA. AMERICA - CARTAGENA,26/09/2016,442927.54,4476728.35,40.439245,-3.672940
2,1469,704,AVDA. CIUDAD BARCELONA - MENÉNDEZ PELAYO,02/02/2016,442264.49,4472835.47,40.404130,-3.680405
3,539,701,"AVDA. FILIPINAS, 18",08/12/2009,439774.02,4476846.37,40.440086,-3.710132
4,541,704,AVDA. ILUSTRACIÓN - BETANZOS,30/11/2009,439643.33,4481335.97,40.480520,-3.712100
5,769,702,"AVDA. MEDITERRÁNEO, 32",12/12/2011,442886.68,4473142.79,40.406941,-3.673100
6,1547,703,CEA BERMÚDEZ - VALLEHERMOSO,02/02/2016,439896.40,4476708.97,40.438857,-3.708676
7,770,701,"FRANCISCO SILVELA, 62",12/12/2011,442747.54,4476282.08,40.435212,-3.675022
8,1551,704,"FRANCISCO SILVELA, 99",NaN,442354.20,4476759.67,40.439487,-3.679703
9,1550,703,"JOAQUIN COSTA, 36",NaN,442232.35,4476921.09,40.440933,-3.681154
10,728,701,JOAQUIN COSTA - VELAZQUEZ,26/09/2016,442051.85,4477144.55,40.442934,-3.683303
11,1468,702,JOSE ABASCAL - SANTA ENGRACIA,02/02/2016,440561.57,4476668.95,40.438544,-3.700830
12,768,701,MENÉNDEZ PELAYO - NIÑO JESÚS,23/02/2012,442516.73,4474002.28,40.414659,-3.677538
13,1470,706,MONFORTE DE LEMOS - FINISTERRE,26/09/2016,440473.44,4481252.09,40.479824,-3.702299
14,618,702,O'DONNELL CARRIL CENTRAL,08/07/2010,443315.10,4474707.54,40.421067,-3.668191
15,439,702,"PO CASTELLANA, 105",30/11/2009,441447.02,4478449.26,40.454645,-3.690555
16,545,701,"PO CASTELLANA, 167",26/10/2006,441514.60,4479282.59,40.462156,-3.689835
17,746,703,"SINESIO DELGADO GTA P, CEBRERO",30/06/2014,439714.24,4480306.29,40.471250,-3.711165

In [51]:
df.to_csv(filepath[:-3]+"csv", index=False)